_security_logout:
    resource: security.route_loader.logout
    type: service

# security:
#     enable_authenticator_manager: true

#     password_hashers:
#         App\Entity\User: auto

#     providers:
#         app_user_provider:
#             entity:
#                 class: App\Entity\User
#                 property: email

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         login:
#             pattern: ^/api/login
#             stateless: true
#             json_login:
#                 check_path: /api/login
#                 username_path: email
#                 password_path: password
#             provider: app_user_provider

#         api:
#             pattern: ^/api
#             stateless: true
#             authenticator:
#                 - lexik_jwt_authentication.jwt_token_authenticator

#     access_control:
#         - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
